use std::path::Path;
use std::fs;
use std::io::{self, BufWriter, Write};

const STDLIB_DIR: &str = "src/stdlib";
const EXCLUDED: &[&str] = &[
    "README.md",
    "LICENSE",
    "eslint.config_partial.mjs",
];

fn main() -> io::Result<()> {
    println!("cargo:rerun-if-changed={}", STDLIB_DIR);

    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR")
        .expect("CARGO_MANIFEST_DIR not set");
    let stdlib_dir = Path::new(&manifest_dir).join(STDLIB_DIR);
    let dest = Path::new(&manifest_dir).join("src/embedded_stdlib.rs");

    let mut files: Vec<String> = Vec::new();
    collect_files(&stdlib_dir, &stdlib_dir, &mut files);
    files.sort();

    let mut out = BufWriter::new(fs::File::create(dest)?);

    writeln!(out, "// Auto-generated by build.rs")?;
    writeln!(out, "// Do not edit manually.")?;
    writeln!(out)?;
    writeln!(out, "/// Look up an embedded stdlib file by its relative path")?;
    writeln!(out, "/// (e.g. \"fs.js\", \"path/posix.js\").")?;
    writeln!(out, "/// The JS source is directly embedded as string literals.")?;
    writeln!(out, "pub fn get(path: &str) -> Option<&'static str> {{")?;
    writeln!(out, "    match path {{")?;

    for rel_str in &files {
        let abs_path = stdlib_dir.join(&rel_str);
        let content = fs::read_to_string(&abs_path)?;

        // Determine minimum number of raw string hash delimiters needed
        // so that `"##` sequences inside the content don't break the literal.
        let hash_count = needed_hash_delimiters(&content);
        let hashes = "#".repeat(hash_count);

        write!(out, "        {:?} => Some(r", rel_str)?;
        write!(out, "{}", hashes)?;
        write!(out, "\"")?;
        write!(out, "{}", content)?;
        write!(out, "\"")?;
        write!(out, "{}", hashes)?;
        writeln!(out, "),")?;
    }

    writeln!(out, "        _ => None,")?;
    writeln!(out, "    }}")?;
    writeln!(out, "}}")?;

    out.flush()?;
    Ok(())
}

fn collect_files(base: &Path, dir: &Path, files: &mut Vec<String>) {
    for entry in fs::read_dir(dir).unwrap() {
        let entry = entry.unwrap();
        let path = entry.path();
        if path.is_dir() {
            collect_files(base, &path, files);
        } else {
            let name = path.file_name()
                .and_then(|n| n.to_str())
                .unwrap_or("");
            if EXCLUDED.contains(&name) {
                continue;
            }
            let ext = path.extension()
                .and_then(|e| e.to_str())
                .unwrap_or("");
            if matches!(ext, "js" | "mjs" | "cjs" | "json") {
                if let Ok(rel) = path.strip_prefix(base) {
                    let rel_str = rel.to_str()
                        .unwrap()
                        .replace('\\', "/");
                    files.push(rel_str);
                }
            }
        }
    }
}

/// Count the longest run of `#` that appears right after a `"` in the content.
/// The raw string literal `r##"..."##` breaks if the content contains `"##`,
/// so we need at least `max_run + 1` hash delimiters.
fn needed_hash_delimiters(content: &str) -> usize {
    let mut max_run = 0;
    let mut current = 0;
    let mut after_quote = false;

    for ch in content.chars() {
        match ch {
            '"' => {
                if after_quote && current > max_run {
                    max_run = current;
                }
                after_quote = true;
                current = 0;
            }
            '#' if after_quote => {
                current += 1;
            }
            _ => {
                if after_quote && current > max_run {
                    max_run = current;
                }
                after_quote = false;
                current = 0;
            }
        }
    }
    if after_quote && current > max_run {
        max_run = current;
    }

    max_run + 1
}
