'use strict';

const {
    isMainThread,
    isInternalThread,
    SHARE_ENV,
    threadId,
    Worker,
    receiveMessageOnPort,
    getEnvironmentData,
    setEnvironmentData,
    resourceLimits,
    MessagePort,
    MessageChannel,
    BroadcastChannel,
    markAsUntransferable,
    isMarkedAsUntransferable,
    moveMessagePortToContext,
    markAsUncloneable,
} = require('internal/worker');

module.exports = {
    isMainThread,
    isInternalThread,
    MessagePort,
    MessageChannel,
    markAsUncloneable,
    markAsUntransferable,
    isMarkedAsUntransferable,
    moveMessagePortToContext,
    receiveMessageOnPort,
    resourceLimits,
    setEnvironmentData,
    getEnvironmentData,
    SHARE_ENV,
    threadId,
    threadName: 'main',
    Worker,
    parentPort: null,
    workerData: null,
    BroadcastChannel,
};
